import { ActivityType } from "types/strava/enums"

export const activityTypeEmojis = {
  [ActivityType.AlpineSki]: "⛷",
  [ActivityType.BackcountrySki]: "⛷",
  [ActivityType.Canoeing]: "🚣",
  [ActivityType.Crossfit]: "💪",
  [ActivityType.EBikeRide]: "🚴🏻",
  [ActivityType.Elliptical]: "🚴🏻",
  [ActivityType.Hike]: "🥾",
  [ActivityType.IceSkate]: "⛸",
  [ActivityType.InlineSkate]: "🛼",
  [ActivityType.Kayaking]: "🚣",
  [ActivityType.Kitesurf]: "🪁",
  [ActivityType.NordicSki]: "⛷",
  [ActivityType.Ride]: "🚴🏻",
  [ActivityType.RockClimbing]: "🧗",
  [ActivityType.RollerSki]: "⛷",
  [ActivityType.Rowing]: "🚣",
  [ActivityType.Run]: "🏃",
  [ActivityType.Snowboard]: "🏂",
  [ActivityType.Snowshoe]: "🎿",
  [ActivityType.StairStepper]: "🪜",
  [ActivityType.StandUpPaddling]: "🧍",
  [ActivityType.Surfing]: "🏄",
  [ActivityType.Swim]: "🏊",
  [ActivityType.VirtualRide]: "📀",
  [ActivityType.Walk]: "🚶",
  [ActivityType.WeightTraining]: "🏋️",
  [ActivityType.Windsurf]: "🏄",
  [ActivityType.Workout]: "🏋️",
  [ActivityType.Yoga]: "🧘",
}
